[tool.poetry]
name = "hangman"
version = "0.1.0"
description = ""
authors = ["Common Lisper <atosdo@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 120
